version: "3.9"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  webapp:
    restart: always
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && 
      python manage.py migrate 
      && poetry run python -u manage.py runserver 0.0.0.0:8000
      && celery -A main flower --port=5555"

  worker:
    restart: always
    build: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - webapp
    command: 'celery -A main worker -l info'

  beat:
    restart: always
    build: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - webapp
      - worker
    command: 'celery -A main beat -l info'


  flower:
    restart: always
    build: .
    volumes:
      - ./:/app
    ports:
      - 5555:5555
    depends_on:
      - worker
      - redis
    command: celery -A main flower
